### ISSUE TITLE
Support for less v4

### ISSUE THREAD

**Issue by mdel-cm** [gulp-community/gulp-less#312]
Hi,

I just tried to upgrade to less 4.0.0 in an existing project, which gives me the following error:
```
Error: less version 4.0.0 is not currently supported
    at Object.exports.load (C:\Users\mdel\git\devbox\git\sensum\node_modules\accord\lib\index.js:29:13)
    at Object.<anonymous> (C:\Users\mdel\git\devbox\git\sensum\node_modules\gulp-less\index.js:9:29)
    // Longer stack trace ...
```
Node: 14.15.1
Yarn: 1.22.10

The actual error message seems to originate in accord. Let me know if I should I should open an issue at their repository as well or if you need any more details.

Thanks and best regards,
Michael

**Comment by stevelacy** [comment]
@mdel-cm Yes, please open an issue on the accord repo. I will see if I have time to add 4.0 support as well

**Comment by StreetStrider** [comment]
Isn't it (in general) that `less` should be declared as a peer dep?

**Comment by mdel-cm** [comment]
Sorry, Christmas holidays happened and I missed following up here. Just created the issue at the accord repo today ...

**Comment by lubber-de** [comment]
accord seems to be a dead repo since 2 years. Could you try to support less 4 by yourself without using accord?

**Comment by stamminator** [comment]
Am I missing something? How is it that the de facto library for compiling LESS in gulp, arguably the most popular Node task runner out there, has not supported the latest major version of that task runner that came out over three years ago?

**Comment by StreetStrider** [comment]
@stamminator I think that's totally ordinary, because both gulp and less (and preprocessors in general) are not in their's prime age. I think most of the teams with modern tech stacks are already migrated or migrating in one of the popular directions like css-in-js or css modules with postcss transformations while legacy stacks just ok with non-edge versions of their build utilities.

**Comment by stamminator** [comment]
@StreetStrider That's a very good point, but I don't like what you're saying because it sounds to me like I'm overdue on learning the latest and greatest in tooling. I just want things to stay still, but alas, this is the JS ecosystem after all.

**Comment by StreetStrider** [comment]
@stamminator I'm a huge fan of less and gulp. And I also think that bundling css with js bundler is generally not a good idea. However, in my experience that's just facts, there is declining interest in both gulp and preprocessors, sadly.

**Comment by RaptorCZ** [comment]
So, any solution?

**Comment by contra** [comment]
Hey all - just thought I would chime in here.

A number of gulp plugins relied on https://github.com/jescalan/accord which appears to be unmaintained now and not updating things to the latest versions - this is going to require any plugin that relies on accord to be rewritten to use the libraries directly, or somebody needs to fork accord and update things.

Given that LESS is not so popular anymore (most people are using postcss), it isn't super high on the priority list for the team to rewrite the plugin solely so that it supports a newer version of LESS. That being said, if somebody is using LESS and feels passionately that they need to use LESS V4 and wants to rewrite this plugin to switch off of accord - gulp plugins are extremely simple and easy to write, and I would happily accept a PR. A simple less compiling plugin for gulp will probably clock in at like 30 lines of code.

**Comment by MisterLuffy** [comment]
Hi Chris, I have created a [pull request](https://github.com/gulp-community/gulp-less/pull/313) to support less v4. Please check it. Thanks

**Comment by contra** [comment]
Published as v5 - thank you @MisterLuffy!
